### ISSUE TITLE
Graphic for blog post about securing dashboard2

### ISSUE THREAD

**Issue by Steve-Mcl** [FlowFuse/website#1102] opened 2023-09-07 09:46 UTC
### Description

**Considerations:**
- Graphic is for a website blog post
- minimal text - graphic should infer Node-RED, New Dashboard offering from FlowFuse, secure access

**Inspirations:**
- [this graphic](https://assets.toptal.io/images?url=https%3A%2F%2Fbs-uploads.toptal.io%2Fblackfish-uploads%2Fcomponents%2Fblog_post_page%2Fcontent%2Fcover_image_file%2Fcover_image%2F1295887%2Fregular_1708x683_Untitled-fa88f2cd4127cef607cf9bcc1160f467.png) feels nice - a lock and key over a flowfuse-node-red-dashboard - possibly one of the previously developed dashboard graphics we have (for consistency?)

**Comment by Yndira-FlowForge** [comment] 2023-10-03 07:35
I think this is a duplicate of [#1190](https://github.com/FlowFuse/website/issues/1190). I'm closing this one.

**Closed** 2023-10-03 07:35 UTC
Labels: task, design, artwork
